PREFIX ex: <http://example.com/<

SELECT ?s1 ?d10s1 ?d2s1 ?d9s1 ?d6s1 ?d4s1
WHERE { 
?s1 ex:d10 ?d10s1 .
?s1 ex:d2 ?d2s1 .
?s1 ex:d9 ?d9s1 .
?s1 ex:d6 ?d6s1 .
?s1 ex:d4 ?d4s1 .
OPTIONAL { 
?s1 ex:d10 ?d10s1 .
?s2 ex:d10 ?d10s2 .
?s1 ex:d2 ?d2s1 .
?s2 ex:d2 ?d2s2 .
?s1 ex:d9 ?d9s1 .
?s2 ex:d9 ?d9s2 .
?s1 ex:d6 ?d6s1 .
?s2 ex:d6 ?d6s2 .
?s1 ex:d4 ?d4s1 .
?s2 ex:d4 ?d4s2 .
FILTER ( ?d10s2 <= ?d10s1 && ?d2s2 <= ?d2s1 && ?d9s2 <= ?d9s1 && ?d6s2 <= ?d6s1 && ?d4s2 <= ?d4s1 && ( ?d10s2 < ?d10s1 || ?d2s2 < ?d2s1 || ?d9s2 < ?d9s1 || ?d6s2 < ?d6s1 || ?d4s2 < ?d4s1  ) )
}
	FILTER (!BOUND(?s2))
}
