PREFIX ex: <http://example.com/>

SELECT ?s1 ?d4s1 ?d2s1 ?d8s1 ?d6s1
WHERE { 
?s1 ex:d4 ?d4s1 .
?s1 ex:d2 ?d2s1 .
?s1 ex:d8 ?d8s1 .
?s1 ex:d6 ?d6s1 .
}
SKYLINE OF ?d4s1 MAX, ?d2s1 MAX, ?d8s1 MAX, ?d6s1 MIN
