PREFIX ex: <http://example.com/>

SELECT ?s1 ?d3s1 ?d5s1 ?d1s1 ?d2s1
WHERE { 
?s1 ex:d3 ?d3s1 .
?s1 ex:d5 ?d5s1 .
?s1 ex:d1 ?d1s1 .
?s1 ex:d2 ?d2s1 .
}
SKYLINE OF ?d3s1 MIN, ?d5s1 MAX, ?d1s1 MIN, ?d2s1 MAX
