PREFIX ex: <http://example.com/>

SELECT ?s1 ?d8s1 ?d4s1
WHERE { 
?s1 ex:d8 ?d8s1 .
?s1 ex:d4 ?d4s1 .
OPTIONAL { 
?s1 ex:d8 ?d8s1 .
?s2 ex:d8 ?d8s2 .
?s1 ex:d4 ?d4s1 .
?s2 ex:d4 ?d4s2 .
FILTER ( ?d8s2 <= ?d8s1 && ?d4s2 <= ?d4s1 && ( ?d8s2 < ?d8s1 || ?d4s2 < ?d4s1  ) )
}
	FILTER (!BOUND(?s2))
}
