PREFIX ex: <http://example.com/>

SELECT ?s1 ?d9s1 ?d6s1
WHERE { 
?s1 ex:d9 ?d9s1 .
?s1 ex:d6 ?d6s1 .
OPTIONAL { 
?s1 ex:d9 ?d9s1 .
?s2 ex:d9 ?d9s2 .
?s1 ex:d6 ?d6s1 .
?s2 ex:d6 ?d6s2 .
FILTER ( ?d9s2 >= ?d9s1 && ?d6s2 >= ?d6s1 && ( ?d9s2 > ?d9s1 || ?d6s2 > ?d6s1  ) )
}
	FILTER (!BOUND(?s2))
}
