PREFIX ex: <http://example.com/>

SELECT ?s1 ?d7s1 ?d4s1 ?d1s1
WHERE { 
?s1 ex:d7 ?d7s1 .
?s1 ex:d4 ?d4s1 .
?s1 ex:d1 ?d1s1 .
OPTIONAL { 
?s1 ex:d7 ?d7s1 .
?s2 ex:d7 ?d7s2 .
?s1 ex:d4 ?d4s1 .
?s2 ex:d4 ?d4s2 .
?s1 ex:d1 ?d1s1 .
?s2 ex:d1 ?d1s2 .
FILTER ( ?d7s2 <= ?d7s1 && ?d4s2 <= ?d4s1 && ?d1s2 <= ?d1s1 && ( ?d7s2 < ?d7s1 || ?d4s2 < ?d4s1 || ?d1s2 < ?d1s1  ) )
}
	FILTER (!BOUND(?s2))
}
