PREFIX ex: <http://example.com/>

SELECT ?s1 ?d7s1 ?d3s1 ?d9s1 ?d5s1 ?d6s1 ?d1s1
WHERE { 
?s1 ex:d7 ?d7s1 .
?s1 ex:d3 ?d3s1 .
?s1 ex:d9 ?d9s1 .
?s1 ex:d5 ?d5s1 .
?s1 ex:d6 ?d6s1 .
?s1 ex:d1 ?d1s1 .
}
SKYLINE OF ?d7s1 MIN, ?d3s1 MIN, ?d9s1 MIN, ?d5s1 MIN, ?d6s1 MIN, ?d1s1 MIN
